package
{
	import mx.collections.ArrayCollection;
	import mx.collections.ICollectionView;
	import mx.collections.Sort;
	
	public class WordListUtils
	{
		public static function getWordList():ArrayCollection
		{
			var wordlist:ArrayCollection = new ArrayCollection();
			wordlist.addItem({word:"abacus", definition:"frame with balls for calculating"})
			wordlist.addItem({word:"abate", definition:"to lessen to subside"})
			wordlist.addItem({word:"abdication", definition:"giving up control authority"})
			wordlist.addItem({word:"aberration", definition:"straying away from what is normal"})
			wordlist.addItem({word:"abet", definition:"help/encourage smb (in doing wrong)"})
			wordlist.addItem({word:"abeyance", definition:"suspended action"})
			wordlist.addItem({word:"abhor", definition:"to hate to detest"})
			wordlist.addItem({word:"abide", definition:"be faithful to endure"})
			wordlist.addItem({word:"abjure", definition:"promise or swear to give up"})
			wordlist.addItem({word:"abraded", definition:"rubbed off worn away by friction"})
			wordlist.addItem({word:"abrogate", definition:"repeal or annul by authority"})
			wordlist.addItem({word:"abscond", definition:"to go away suddenly (to avoid arrest)"})
			wordlist.addItem({word:"abstruse", definition:"difficult to comprehend obscure"})
			wordlist.addItem({word:"abut", definition:"border on"})
			wordlist.addItem({word:"abysmal", definition:"bottomless extreme"})
			wordlist.addItem({word:"acarpous", definition:"effete no longer fertile worn out"})
			wordlist.addItem({word:"acclaimed", definition:"welcomed with shouts and approval"})
			wordlist.addItem({word:"accolade", definition:"praise approval"})
			wordlist.addItem({word:"accretion", definition:"the growing of separate things into one"})
			wordlist.addItem({word:"adamant", definition:"kind of stone inflexible"})
			wordlist.addItem({word:"admonitory", definition:"containing warning"})
			wordlist.addItem({word:"adorn", definition:"add beauty decorate"})
			wordlist.addItem({word:"adulteration", definition:"making unpure poorer in quality"})
			wordlist.addItem({word:"affable", definition:"polite and friendly"})
			wordlist.addItem({word:"affinity", definition:"close connection relationship"})
			wordlist.addItem({word:"aggravate", definition:"make worse irritate"})
			wordlist.addItem({word:"agile", definition:"active quick-moving"})
			wordlist.addItem({word:"agog", definition:"eager/excited"})
			wordlist.addItem({word:"ail", definition:"trouble be ill"})
			wordlist.addItem({word:"alacrity", definition:"eager and cheerful readiness"})
			wordlist.addItem({word:"alcove", definition:"recess/partially enclosed place"})
			wordlist.addItem({word:"allegiance", definition:"duty support loyalty"})
			wordlist.addItem({word:"alleviate", definition:"make (pain) easier to bear"})
			wordlist.addItem({word:"alloy", definition:"to debase by mixing with something inferior"})
			wordlist.addItem({word:"aloof", definition:"reserved indifferent"})
			wordlist.addItem({word:"amalgamate", definition:"mix combine unite societies"})
			wordlist.addItem({word:"ambidextrous", definition:"able to use the left hand or the right equally well"})
			wordlist.addItem({word:"ambiguous", definition:"doubtful uncertain"})
			wordlist.addItem({word:"ambivalent", definition:"having both of two contrary meanings"})
			wordlist.addItem({word:"ameliorate", definition:"improve make better"})
			wordlist.addItem({word:"amortize", definition:"end (a debt) by setting aside money"})
			wordlist.addItem({word:"anguish", definition:"severe suffering"})
			wordlist.addItem({word:"animosity", definition:"strong dislike"})
			wordlist.addItem({word:"antidote", definition:"medicine used against a poison or a disease"})
			wordlist.addItem({word:"antithetical", definition:"direct opposing"})
			wordlist.addItem({word:"apartheid", definition:"brutal racial discrimination"})
			wordlist.addItem({word:"aplomb", definition:"self-confidence"})
			wordlist.addItem({word:"apostate", definition:"one who abandons long-held religious or political convictions"})
			wordlist.addItem({word:"apotheosis", definition:"deification glorification to godliness"})
			wordlist.addItem({word:"appease", definition:"make quiet or calm"})
			wordlist.addItem({word:"apprehensive", definition:"grasping understanding fear unhappy feeling about future"})
			wordlist.addItem({word:"apprise", definition:"give notice to inform"})
			wordlist.addItem({word:"approbation", definition:"approval"})
			wordlist.addItem({word:"apropos", definition:"appropriate to the situation apt"})
			wordlist.addItem({word:"apt", definition:"well-suited quick-witted"})
			wordlist.addItem({word:"arabesque", definition:"a complex ornate design"})
			wordlist.addItem({word:"arboreal", definition:"of connected with trees"})
			wordlist.addItem({word:"ardor", definition:"enthusiasm"})
			wordlist.addItem({word:"arduous", definition:"steep difficult ascent laborious"})
			wordlist.addItem({word:"argot", definition:"jargon slang"})
			wordlist.addItem({word:"arrant", definition:"in the highest degree"})
			wordlist.addItem({word:"arrogance", definition:"proud superior manner of behaviour"})
			wordlist.addItem({word:"articulate", definition:"speak distinctly connect by joints"})
			wordlist.addItem({word:"ascend", definition:"go or come up"})
			wordlist.addItem({word:"ascertain", definition:"get to know"})
			wordlist.addItem({word:"ascetic", definition:"practicing self-denial austere stark"})
			wordlist.addItem({word:"ascribe", definition:"consider to be the origin of or belonging to"})
			wordlist.addItem({word:"aseptic", definition:"surgically clean"})
			wordlist.addItem({word:"asperity", definition:"roughness harshness ill temper irritability"})
			wordlist.addItem({word:"aspersion", definition:"slander"})
			wordlist.addItem({word:"assail", definition:"with attack violently"})
			wordlist.addItem({word:"assiduous", definition:"diligent hard-working sedulous"})
			wordlist.addItem({word:"assuage", definition:"make smth (pain desire) less"})
			wordlist.addItem({word:"asterisk", definition:"the mark * (e.g.. omitted letters)"})
			wordlist.addItem({word:"astringent", definition:"substance that shrinks"})
			wordlist.addItem({word:"astute", definition:"clever quick at seeing to get an advantage"})
			wordlist.addItem({word:"atonement", definition:"repayment death of Jesus"})
			wordlist.addItem({word:"attenuate", definition:"make thin. weaken enervate"})
			wordlist.addItem({word:"attune", definition:"bring into harmony"})
			wordlist.addItem({word:"audacious", definition:"daring foolishly bold impudent"})
			wordlist.addItem({word:"augury", definition:"omen sign"})
			wordlist.addItem({word:"august", definition:"majestic venerable"})
			wordlist.addItem({word:"auspicious", definition:"favorable successful prosperous"})
			wordlist.addItem({word:"austere", definition:"severely moral and strict simple and plain"})
			wordlist.addItem({word:"auxiliary", definition:"helping supporting"})
			wordlist.addItem({word:"aver", definition:"affirm assert prove justify"})
			wordlist.addItem({word:"aversion", definition:"strong dislike"})
			wordlist.addItem({word:"avid", definition:"eager greedy"})
			wordlist.addItem({word:"avow", definition:"admit. Declare openly"})
			wordlist.addItem({word:"baleful", definition:"harmful ominous causing evil"})
			wordlist.addItem({word:"balk", definition:"obstacle purposely to get on the way of"})
			wordlist.addItem({word:"baneful", definition:"causing harm or ruin pernicious destructive"})
			wordlist.addItem({word:"barrage", definition:"artificial obstacle built across a river"})
			wordlist.addItem({word:"barren", definition:"not good enough unable to have young ones without value"})
			wordlist.addItem({word:"bask", definition:"in enjoy warmth and light"})
			wordlist.addItem({word:"beatify", definition:"to bless make happy or ascribe a virtue to"})
			wordlist.addItem({word:"bedizen", definition:"to adorn especially in a cheap showy manner"})
			wordlist.addItem({word:"belabor", definition:"beat hard"})
			wordlist.addItem({word:"bellicose", definition:"belligerent pugnacious warlike"})
			wordlist.addItem({word:"belligerent", definition:"(person nation) waging war"})
			wordlist.addItem({word:"benefactor", definition:"person who has given help"})
			wordlist.addItem({word:"benevolence", definition:"wish or activity in doing good"})
			wordlist.addItem({word:"benign", definition:"kind and gentle mild (climate)"})
			wordlist.addItem({word:"bequest", definition:"arrangement to give smth at death"})
			wordlist.addItem({word:"berate", definition:"scold sharply"})
			wordlist.addItem({word:"bereft", definition:"rob or dispossess of smth (material)"})
			wordlist.addItem({word:"bewilder", definition:"puzzle confuse"})
			wordlist.addItem({word:"bigot", definition:"stubborn narrow-minded person"})
			wordlist.addItem({word:"bilge", definition:"bulge the protuberance of a cask"})
			wordlist.addItem({word:"blandishment", definition:"flattery coaxing"})
			wordlist.addItem({word:"blandness", definition:"polite manner comforting uninteresting"})
			wordlist.addItem({word:"blatant", definition:"noisy and rough"})
			wordlist.addItem({word:"blithe", definition:"cheerful casual carefree"})
			wordlist.addItem({word:"bogus", definition:"sham counterfeit not genuine"})
			wordlist.addItem({word:"boisterous", definition:"loud noisy rough lacking restraint"})
			wordlist.addItem({word:"bolster", definition:"give greatly needed support"})
			wordlist.addItem({word:"boorish", definition:"crude offensive rude"})
			wordlist.addItem({word:"brash", definition:"hasty rush cheeky saucy"})
			wordlist.addItem({word:"brass", definition:"yellow metal (mixing copper and zinc)"})
			wordlist.addItem({word:"brazen", definition:"made of brass"})
			wordlist.addItem({word:"breach", definition:"opening broken place breaking"})
			wordlist.addItem({word:"brittle", definition:"easily broken"})
			wordlist.addItem({word:"broach", definition:"bring up announce begin to talk about"})
			wordlist.addItem({word:"brook", definition:"to tolerate endure"})
			wordlist.addItem({word:"buoyant", definition:"able to float light-hearted"})
			wordlist.addItem({word:"burgeon", definition:"grow forth send out buds"})
			wordlist.addItem({word:"burnish", definition:"to polish rub to a shine"})
			wordlist.addItem({word:"cabal", definition:"a scheme or plot a group of plotters"})
			wordlist.addItem({word:"cadge", definition:"to beg to get by begging"})
			wordlist.addItem({word:"cajole", definition:"use flattery or deceit to persuade"})
			wordlist.addItem({word:"calipers", definition:"metal supports attached to the legs measuring instrument"})
			wordlist.addItem({word:"calumny", definition:"slander aspersion"})
			wordlist.addItem({word:"candid", definition:"frank straight-forward"})
			wordlist.addItem({word:"cant", definition:"insincere talk/jargon"})
			wordlist.addItem({word:"cantankerous", definition:"bad-tempered/quarrelsome"})
			wordlist.addItem({word:"canvass", definition:"discuss thoroughly sort of touting"})
			wordlist.addItem({word:"castigate", definition:"to chastise correct by punishing"})
			wordlist.addItem({word:"castigation", definition:"severe punishment"})
			wordlist.addItem({word:"catalyst", definition:"substance that causes speeding up"})
			wordlist.addItem({word:"caustic", definition:"biting sarcastic"})
			wordlist.addItem({word:"censure", definition:"expression of blame or disapproval a rebuke"})
			wordlist.addItem({word:"centurion", definition:"leader of a unit of 100 soldiers"})
			wordlist.addItem({word:"chary", definition:"cautious wary"})
			wordlist.addItem({word:"chastened", definition:"corrected punished"})
			wordlist.addItem({word:"chastisement", definition:"punishment"})
			wordlist.addItem({word:"chauvinist", definition:"a blindly devoted patriot"})
			wordlist.addItem({word:"chicanery", definition:"legal trickery/false argument"})
			wordlist.addItem({word:"chisel", definition:"steel tool for shaping materials"})
			wordlist.addItem({word:"churl", definition:"bad-tempered person"})
			wordlist.addItem({word:"clamor", definition:"shout complain with a lot of noise"})
			wordlist.addItem({word:"clientele", definition:"customers"})
			wordlist.addItem({word:"clinch", definition:"come to grips/settle conclusively"})
			wordlist.addItem({word:"cling", definition:"to resist separation"})
			wordlist.addItem({word:"clot", definition:"half-solid lump formed from liquid"})
			wordlist.addItem({word:"cloture", definition:"closing device (in Parliament) to end a debate by voting"})
			wordlist.addItem({word:"coagulation", definition:"change to a thick and solid state"})
			wordlist.addItem({word:"coalescing", definition:"coming together and uniting into one substance"})
			wordlist.addItem({word:"coax", definition:"get smb to do smth by kindness"})
			wordlist.addItem({word:"coda", definition:"passage that completes a piece of music"})
			wordlist.addItem({word:"coddle", definition:"treat with care and tenderness"})
			wordlist.addItem({word:"coerce", definition:"compel to force to make obedient"})
			wordlist.addItem({word:"coeval", definition:"of the same period coexisting"})
			wordlist.addItem({word:"cogent", definition:"strong convincing"})
			wordlist.addItem({word:"cogitate", definition:"think deeply mediate"})
			wordlist.addItem({word:"cognizant", definition:"being fully aware of"})
			wordlist.addItem({word:"colander", definition:"bowl-shaped vessel with many holes used to drain off water"})
			wordlist.addItem({word:"collusion", definition:"secret agreement for a deceitful purpose"})
			wordlist.addItem({word:"combustion", definition:"process of burning"})
			wordlist.addItem({word:"commemorate", definition:"keep the memory of"})
			wordlist.addItem({word:"commodious", definition:"having plenty of space for what is needed"})
			wordlist.addItem({word:"commuter", definition:"person who travels regularly"})
			wordlist.addItem({word:"complaisance", definition:"tending to comply obliging willingness to please"})
			wordlist.addItem({word:"compunction", definition:"feeling of regret for one's action"})
			wordlist.addItem({word:"conceal", definition:"hide keep secret"})
			wordlist.addItem({word:"conceit", definition:"over-high opinion of too much pride"})
			wordlist.addItem({word:"conciliatory", definition:"reconciling soothing comforting mollifying"})
			wordlist.addItem({word:"concord", definition:"agreement or harmony"})
			wordlist.addItem({word:"concur", definition:"agree in opinion happen together"})
			wordlist.addItem({word:"condense", definition:"increase in density strength make laconic"})
			wordlist.addItem({word:"condone", definition:"forgive"})
			wordlist.addItem({word:"congeal", definition:"make or become stiff and solid"})
			wordlist.addItem({word:"conjoin", definition:"to join together"})
			wordlist.addItem({word:"connoisseur", definition:"a person with good judgement (e.g.. in art)"})
			wordlist.addItem({word:"connotation", definition:"suggestion in addition to"})
			wordlist.addItem({word:"consequential", definition:"pompous self important"})
			wordlist.addItem({word:"console", definition:"give comfort or sympathy to"})
			wordlist.addItem({word:"conspicuous", definition:"easily seen remarkable"})
			wordlist.addItem({word:"consternation", definition:"surprise and fear dismay"})
			wordlist.addItem({word:"constrain", definition:"compel"})
			wordlist.addItem({word:"constrict", definition:"make tight or smaller"})
			wordlist.addItem({word:"consume", definition:"get to the end of"})
			wordlist.addItem({word:"consummate", definition:"perfect/make perfect/complete"})
			wordlist.addItem({word:"contemn", definition:"to scorn or despise"})
			wordlist.addItem({word:"contentious", definition:"argumentative pugnacious combative quarrelsome"})
			wordlist.addItem({word:"contiguous", definition:"touching neighboring near"})
			wordlist.addItem({word:"contrite", definition:"filled with deep sorrow for wrongdoing"})
			wordlist.addItem({word:"contumacious", definition:"insubordinate rebellious"})
			wordlist.addItem({word:"conundrum", definition:"a riddle dilemma enigma"})
			wordlist.addItem({word:"conviction", definition:"convincing firm belief"})
			wordlist.addItem({word:"convoke", definition:"call together summon"})
			wordlist.addItem({word:"convoluted", definition:"complicated coiled twisted"})
			wordlist.addItem({word:"cordial", definition:"warm and sincere"})
			wordlist.addItem({word:"cordon", definition:"line (of police acting as a guard)"})
			wordlist.addItem({word:"cornucopia", definition:"abundant supply"})
			wordlist.addItem({word:"corporeal", definition:"physical of or for the body"})
			wordlist.addItem({word:"correlate", definition:"have a mutual relation"})
			wordlist.addItem({word:"corroboration", definition:"additional strengthening evidence"})
			wordlist.addItem({word:"countenance", definition:"to favor or approve of"})
			wordlist.addItem({word:"counterfeit", definition:"forgery"})
			wordlist.addItem({word:"countervail", definition:"counterbalance"})
			wordlist.addItem({word:"covert", definition:"disguised"})
			wordlist.addItem({word:"covetous", definition:"eagerly desirous"})
			wordlist.addItem({word:"cower", definition:"crouch shrink back"})
			wordlist.addItem({word:"coy", definition:"shy/modest (esp of a girl)"})
			wordlist.addItem({word:"crass", definition:"very great (es. stupidity)"})
			wordlist.addItem({word:"cravat", definition:"piece of linen worn as a necktie"})
			wordlist.addItem({word:"craven", definition:"cowardly"})
			wordlist.addItem({word:"crease", definition:"line made by crushing white line on the ground in cricket"})
			wordlist.addItem({word:"credulity", definition:"too great a readiness to believe things"})
			wordlist.addItem({word:"credulous", definition:"ready to believe things"})
			wordlist.addItem({word:"crush", definition:"press lose shape subdue overwhelm"})
			wordlist.addItem({word:"cryptic", definition:"secret with a hidden meaning"})
			wordlist.addItem({word:"cumbersome", definition:"burdensome heavy and awkward to carry"})
			wordlist.addItem({word:"curmudgeon", definition:"bad-tempered person"})
			wordlist.addItem({word:"curriculum", definition:"course of study"})
			wordlist.addItem({word:"cursory", definition:"quick hurried"})
			wordlist.addItem({word:"curtail", definition:"make shorter then was planned"})
			wordlist.addItem({word:"dainty", definition:"pretty/delicate(food)/difficult to please"})
			wordlist.addItem({word:"daunt", definition:"intimidate make fearful"})
			wordlist.addItem({word:"dawdler", definition:"person who is slow waste of time"})
			wordlist.addItem({word:"dearth", definition:"shortage"})
			wordlist.addItem({word:"debacle", definition:"a breakup overthrow sudden disaster"})
			wordlist.addItem({word:"decorum", definition:"propriety properness"})
			wordlist.addItem({word:"decree", definition:"order given by authority"})
			wordlist.addItem({word:"decry", definition:"disapprove of"})
			wordlist.addItem({word:"defer", definition:"postpone give way (to show respect)"})
			wordlist.addItem({word:"deferential", definition:"showing respect"})
			wordlist.addItem({word:"defiance", definition:"open disobedience or resistance"})
			wordlist.addItem({word:"delineate", definition:"to portray depict sketch out"})
			wordlist.addItem({word:"deluge", definition:"great flood heavy rush of water"})
			wordlist.addItem({word:"demagogue", definition:"person appealing not to reasons"})
			wordlist.addItem({word:"demur", definition:"to hesitate raise objections"})
			wordlist.addItem({word:"denigrate", definition:"blacken belittle sully defame"})
			wordlist.addItem({word:"denouement", definition:"an outcome or solution the unraveling of a plot"})
			wordlist.addItem({word:"deplete", definition:"use until none remains"})
			wordlist.addItem({word:"deposition", definition:"dethronement depositing"})
			wordlist.addItem({word:"deprave", definition:"make morally bad corrupt"})
			wordlist.addItem({word:"deprecate", definition:"protest against express disapproval of"})
			wordlist.addItem({word:"dereliction", definition:"deserting and leaving to fall into ruins"})
			wordlist.addItem({word:"derision", definition:"ridicule mockery deriding"})
			wordlist.addItem({word:"derivative", definition:"unoriginal obtained from another source"})
			wordlist.addItem({word:"derogatory", definition:"insulting tending to damage"})
			wordlist.addItem({word:"descry", definition:"catch sight of see smth in the distance"})
			wordlist.addItem({word:"desiccant", definition:"substance used to absorb moisture"})
			wordlist.addItem({word:"desuetude", definition:"cessation of use disuse"})
			wordlist.addItem({word:"desultory", definition:"aimless haphazard digressing at random"})
			wordlist.addItem({word:"deter", definition:"discourage hinder"})
			wordlist.addItem({word:"detraction", definition:"slandering verbal attack aspersion"})
			wordlist.addItem({word:"detumescence", definition:"diminishing or lessening of swelling"})
			wordlist.addItem({word:"deviance", definition:"being different in moral standards (from normal)"})
			wordlist.addItem({word:"dexterity", definition:"skill (esp. in handling)"})
			wordlist.addItem({word:"diaphanous", definition:"transparent gauzy"})
			wordlist.addItem({word:"diatribe", definition:"bitter and violent attack in words"})
			wordlist.addItem({word:"diffidence", definition:"shyness"})
			wordlist.addItem({word:"dilate", definition:"speak comprehensively become wider large"})
			wordlist.addItem({word:"disallow", definition:"refuse to allow or accept as a correct"})
			wordlist.addItem({word:"discern", definition:"see with an effort but clearly"})
			wordlist.addItem({word:"discomfit", definition:"confuse embarrass"})
			wordlist.addItem({word:"disconcert", definition:"upset the self-possession of"})
			wordlist.addItem({word:"discountenance", definition:"refuse to approve of"})
			wordlist.addItem({word:"discourse", definition:"speech lecture"})
			wordlist.addItem({word:"discredit", definition:"refuse to believe"})
			wordlist.addItem({word:"discreet", definition:"careful/prudent"})
			wordlist.addItem({word:"discrete", definition:"individually distinct"})
			wordlist.addItem({word:"disdain", definition:"look on with contempt"})
			wordlist.addItem({word:"disencumber", definition:"free from encumbrance"})
			wordlist.addItem({word:"disheveled", definition:"untidy"})
			wordlist.addItem({word:"disingenuous", definition:"sophisticated artful trying to deceive cunning"})
			wordlist.addItem({word:"disinter", definition:"dig up from the earth"})
			wordlist.addItem({word:"dislodge", definition:"move force from the place occupied"})
			wordlist.addItem({word:"dismal", definition:"sad gloomy miserable"})
			wordlist.addItem({word:"disparate", definition:"essentially different"})
			wordlist.addItem({word:"disproof", definition:"proof to the contrary"})
			wordlist.addItem({word:"dissemble", definition:"speak or behave so as to hide smth (in mind)"})
			wordlist.addItem({word:"disseminate", definition:"distribute (esp. ideas)"})
			wordlist.addItem({word:"dissent", definition:"have a different opinion refuse to assent"})
			wordlist.addItem({word:"dissolution", definition:"disintegration looseness in morals"})
			wordlist.addItem({word:"distraught", definition:"distracted violently upset in mind"})
			wordlist.addItem({word:"divergence", definition:"getting farther apart from a point"})
			wordlist.addItem({word:"divestiture", definition:"taking off getting rid of giving up"})
			wordlist.addItem({word:"divulge", definition:"make known smth secret"})
			wordlist.addItem({word:"doggerel", definition:"trivial poorly constructed verse"})
			wordlist.addItem({word:"dogmatic", definition:"positive certain arbitrary without room for discussion"})
			wordlist.addItem({word:"dolt", definition:"stupid fellow"})
			wordlist.addItem({word:"dormant", definition:"in a state of inactivity but awaiting development"})
			wordlist.addItem({word:"dote", definition:"show much fondness center one's attention"})
			wordlist.addItem({word:"drawl", definition:"slow way of speaking"})
			wordlist.addItem({word:"droll", definition:"jesting"})
			wordlist.addItem({word:"drone", definition:"male bee person who isn't self-employed"})
			wordlist.addItem({word:"drowsiness", definition:"feeling sleepy half asleep"})
			wordlist.addItem({word:"dubious", definition:"feeling doubt"})
			wordlist.addItem({word:"dud", definition:"no use person smth that fails"})
			wordlist.addItem({word:"dulcet", definition:"melodious harmonious"})
			wordlist.addItem({word:"dupe", definition:"cheat make a fool of"})
			wordlist.addItem({word:"duplicity", definition:"deliberate deception"})
			wordlist.addItem({word:"duress", definition:"threats to compel smb"})
			wordlist.addItem({word:"dwarf", definition:"person or smb much below the usual size"})
			wordlist.addItem({word:"dynamo", definition:"a generator something that produces electric current"})
			wordlist.addItem({word:"earthenware", definition:"dishes made of baked clay"})
			wordlist.addItem({word:"ebullience", definition:"exuberance outburst of feeling"})
			wordlist.addItem({word:"ebullient", definition:"overflowing with enthusiasm showing excitement"})
			wordlist.addItem({word:"ecumenical", definition:"representing the whole Christian world"})
			wordlist.addItem({word:"edacious", definition:"voracious devouring"})
			wordlist.addItem({word:"eddy", definition:"circular or spiral movement (e.g.. of wind)"})
			wordlist.addItem({word:"edible", definition:"fit to be eaten/not poisonous"})
			wordlist.addItem({word:"effete", definition:"infertile worn out weak"})
			wordlist.addItem({word:"efficacy", definition:"production of a desired result"})
			wordlist.addItem({word:"effluvia", definition:"outflow in a stream of particles a noxious odor or vapor"})
			wordlist.addItem({word:"effrontery", definition:"boldness impudence arrogance"})
			wordlist.addItem({word:"egress", definition:"way out exit"})
			wordlist.addItem({word:"elaborate", definition:"worked out with much care in great detail"})
			wordlist.addItem({word:"elegy", definition:"a lament a melancholy composition"})
			wordlist.addItem({word:"elicit", definition:"draw out"})
			wordlist.addItem({word:"eloquence", definition:"fluent speaking skillful use of language"})
			wordlist.addItem({word:"emaciate", definition:"make thin and weak"})
			wordlist.addItem({word:"embellish", definition:"make beautiful"})
			wordlist.addItem({word:"embezzle", definition:"use in a wrong way for one's own benefit"})
			wordlist.addItem({word:"emote", definition:"stir up excite"})
			wordlist.addItem({word:"empirical", definition:"relying on experiment"})
			wordlist.addItem({word:"encapsulate", definition:"enclose in capsule"})
			wordlist.addItem({word:"encomium", definition:"warm or glowing praise eulogy panegyric"})
			wordlist.addItem({word:"encumbrance", definition:"burden things that get on the way of"})
			wordlist.addItem({word:"endearing", definition:"making dear or liked"})
			wordlist.addItem({word:"endemic", definition:"epidemic"})
			wordlist.addItem({word:"endorse", definition:"write one's name on the back of"})
			wordlist.addItem({word:"enduring", definition:"lasting"})
			wordlist.addItem({word:"enervate", definition:"weaken deprive of strength attenuate"})
			wordlist.addItem({word:"engender", definition:"cause produce give rise to"})
			wordlist.addItem({word:"engrave", definition:"impress deeply"})
			wordlist.addItem({word:"engrossing", definition:"taken up all the time or attention writing in large or formal"})
			wordlist.addItem({word:"engulf", definition:"swallow up"})
			wordlist.addItem({word:"enigma", definition:"smth that is puzzling"})
			wordlist.addItem({word:"enmity", definition:"hatred being an enemy"})
			wordlist.addItem({word:"ensign", definition:"flag/badge"})
			wordlist.addItem({word:"entangle", definition:"put into difficulties"})
			wordlist.addItem({word:"enthral", definition:"please greatly/enslave (fig)"})
			wordlist.addItem({word:"entice", definition:"tempt or persuade"})
			wordlist.addItem({word:"entreat", definition:"ask earnestly"})
			wordlist.addItem({word:"enunciate", definition:"pronounce (words)/express a theory"})
			wordlist.addItem({word:"enzyme", definition:"catalyst"})
			wordlist.addItem({word:"epicurean", definition:"devoted to pleasure (sensuous enjoyment)"})
			wordlist.addItem({word:"epistle", definition:"letter"})
			wordlist.addItem({word:"epithet", definition:"adjective"})
			wordlist.addItem({word:"epitome", definition:"brief summary representative example a typical model"})
			wordlist.addItem({word:"equable", definition:"steady regular"})
			wordlist.addItem({word:"equanimity", definition:"calmness of temperament"})
			wordlist.addItem({word:"equilibrium", definition:"state of being balanced"})
			wordlist.addItem({word:"equipoise", definition:"equal distribution of weight equilibrium"})
			wordlist.addItem({word:"equivocal", definition:"having a double or doubtful meaning suspicious"})
			wordlist.addItem({word:"equivocate", definition:"try to deceive by equivocal language"})
			wordlist.addItem({word:"eradicate", definition:"get rid of pull up by the roots"})
			wordlist.addItem({word:"erratic", definition:"irregular in behaviour or opinion"})
			wordlist.addItem({word:"erudite", definition:"learned scholarly"})
			wordlist.addItem({word:"eschew", definition:"avoid"})
			wordlist.addItem({word:"esoteric", definition:"abstruse intended only for a small circle of"})
			wordlist.addItem({word:"espouse", definition:"marry give one's support to"})
			wordlist.addItem({word:"eulogy", definition:"formal praise panegyric"})
			wordlist.addItem({word:"euphoria", definition:"elation state of pleasant excitement"})
			wordlist.addItem({word:"euthanasia", definition:"easy and painless death"})
			wordlist.addItem({word:"evasive", definition:"tending to evade"})
			wordlist.addItem({word:"evince", definition:"to show clearly to indicate"})
			wordlist.addItem({word:"evoke", definition:"call up bring out"})
			wordlist.addItem({word:"excoriation", definition:"severe criticism"})
			wordlist.addItem({word:"exculpate", definition:"to clear from a charge of guilt"})
			wordlist.addItem({word:"exhaustive", definition:"complete thorough"})
			wordlist.addItem({word:"exigency", definition:"emergency an urgent situation"})
			wordlist.addItem({word:"exoneration", definition:"set smb clear free (e.g.. from blame)"})
			wordlist.addItem({word:"exorbitant", definition:"much too high or great"})
			wordlist.addItem({word:"expatiate", definition:"to roam wander freely"})
			wordlist.addItem({word:"expedient", definition:"likely to be useful for a purpose"})
			wordlist.addItem({word:"expiation", definition:"ending expiring"})
			wordlist.addItem({word:"exploit", definition:"brilliant achievement develop use selfishly"})
			wordlist.addItem({word:"expostulate", definition:"argue earnestly to dissuade correct or protest"})
			wordlist.addItem({word:"expurgate", definition:"to remove obscenity purify censor"})
			wordlist.addItem({word:"exscind", definition:"to cut out cut away"})
			wordlist.addItem({word:"extant", definition:"still in existence"})
			wordlist.addItem({word:"extempore", definition:"without previous thought or preparation"})
			wordlist.addItem({word:"extenuate", definition:"reduce the strength of lessen seriousness partially excuse"})
			wordlist.addItem({word:"extinct", definition:"no longer active"})
			wordlist.addItem({word:"extinguish", definition:"end the existence of/wipe or put out"})
			wordlist.addItem({word:"extirpate", definition:"to destroy exterminate cut out exscind"})
			wordlist.addItem({word:"extol", definition:"praise highly"})
			wordlist.addItem({word:"extort", definition:"obtain by threats violence"})
			wordlist.addItem({word:"extralegal", definition:"outside the law"})
			wordlist.addItem({word:"extricable", definition:"that can be freed"})
			wordlist.addItem({word:"extrovert", definition:"cheerful person"})
			wordlist.addItem({word:"exuberance", definition:"state of growing vigorously being full of life"})
			wordlist.addItem({word:"facetious", definition:"humorous funny jocular"})
			wordlist.addItem({word:"facile", definition:"easily done"})
			wordlist.addItem({word:"fallacious", definition:"based on error"})
			wordlist.addItem({word:"falter", definition:"waver/move in an uncertain manner"})
			wordlist.addItem({word:"fatuous", definition:"without sense foolish self-satisfaction"})
			wordlist.addItem({word:"fawn", definition:"young deer try to win smb's favor"})
			wordlist.addItem({word:"feckless", definition:"lacking purpose or vitality ineffective careless"})
			wordlist.addItem({word:"fecund", definition:"fertile"})
			wordlist.addItem({word:"feint", definition:"pretend"})
			wordlist.addItem({word:"felicitous", definition:"apt suitably expressed well chosen apropos"})
			wordlist.addItem({word:"felon", definition:"person guilty of murder"})
			wordlist.addItem({word:"ferment", definition:"substance become excited"})
			wordlist.addItem({word:"ferocity", definition:"savage cruelty"})
			wordlist.addItem({word:"ferret", definition:"discover by searching search"})
			wordlist.addItem({word:"fervid", definition:"showing earnest feeling"})
			wordlist.addItem({word:"fervor", definition:"warmth of feelings earnestness"})
			wordlist.addItem({word:"fetid", definition:"stinking"})
			wordlist.addItem({word:"fetter", definition:"to shackle put in chains"})
			wordlist.addItem({word:"feud", definition:"bitter quarrel over a long period of time"})
			wordlist.addItem({word:"fidelity", definition:"loyalty accuracy"})
			wordlist.addItem({word:"fidget", definition:"move restlessly make nervous"})
			wordlist.addItem({word:"figurehead", definition:"carved image on the prow of a ship"})
			wordlist.addItem({word:"finesse", definition:"delicate way of dealing with a situation"})
			wordlist.addItem({word:"finical", definition:"too fussy about food clothing etc."})
			wordlist.addItem({word:"finicky", definition:"finical"})
			wordlist.addItem({word:"fission", definition:"splitting or division (esp. of cells)"})
			wordlist.addItem({word:"fixate", definition:"stare at"})
			wordlist.addItem({word:"flak", definition:"criticism/anti-aircraft guns"})
			wordlist.addItem({word:"flamboyant", definition:"brightly colored florid"})
			wordlist.addItem({word:"flaunting", definition:"show off complacently"})
			wordlist.addItem({word:"flax", definition:"pale yellow (hair) a plant"})
			wordlist.addItem({word:"fledged", definition:"able to fly trained experienced"})
			wordlist.addItem({word:"fleet", definition:"number of ships quick-moving"})
			wordlist.addItem({word:"flinch", definition:"draw move back wince"})
			wordlist.addItem({word:"flop", definition:"fail/move/fall clumsily"})
			wordlist.addItem({word:"florid", definition:"very much ornamented naturally red (e.g.. of face)"})
			wordlist.addItem({word:"flout", definition:"reject mock to go against (as in going against tradition)"})
			wordlist.addItem({word:"fluke", definition:"lucky stroke"})
			wordlist.addItem({word:"fluster", definition:"make nervous or confused"})
			wordlist.addItem({word:"foible", definition:"defect of character (a person is wrongly proud)"})
			wordlist.addItem({word:"foil", definition:"prevent from carrying out contrast"})
			wordlist.addItem({word:"foment", definition:"put smth warm (to lessen the pain)"})
			wordlist.addItem({word:"foolproof", definition:"incapable of failure or error"})
			wordlist.addItem({word:"foppish", definition:"like a man who pays too much attention to his clothes"})
			wordlist.addItem({word:"forage", definition:"food for horses and cattle"})
			wordlist.addItem({word:"forbear", definition:"refrain from be patient ancestor"})
			wordlist.addItem({word:"forbearance", definition:"patience willingness to wait"})
			wordlist.addItem({word:"ford", definition:"shallow place in a river (to cross)"})
			wordlist.addItem({word:"forestall", definition:"prevent by taking action in advance preempt"})
			wordlist.addItem({word:"forfeit", definition:"suffer the loss of smth"})
			wordlist.addItem({word:"forge", definition:"workshop for the shaping of metal to shape metal lead"})
			wordlist.addItem({word:"forgery", definition:"counterfeit"})
			wordlist.addItem({word:"forswear", definition:"renounce disallow repudiate"})
			wordlist.addItem({word:"foster", definition:"nurture care for"})
			wordlist.addItem({word:"fracas", definition:"noisy quarrel"})
			wordlist.addItem({word:"fragile", definition:"easily injured broken or destroyed"})
			wordlist.addItem({word:"fragrant", definition:"sweet-smelling"})
			wordlist.addItem({word:"frantic", definition:"wildly excited with joy pain anxiety"})
			wordlist.addItem({word:"frenetic", definition:"frantic frenzied"})
			wordlist.addItem({word:"fret", definition:"worry irritation wear away"})
			wordlist.addItem({word:"fringe", definition:"edge ornamental border part of hair over the forehead"})
			wordlist.addItem({word:"froward", definition:"intractable not willing to yield or comply stubborn"})
			wordlist.addItem({word:"frugal", definition:"careful economical"})
			wordlist.addItem({word:"fulmination", definition:"bitter protest"})
			wordlist.addItem({word:"fulsome", definition:"disgusting offensive due to excessiveness"})
			wordlist.addItem({word:"gainsay", definition:"to deny to oppose"})
			wordlist.addItem({word:"garble", definition:"make unfair selection from facts"})
			wordlist.addItem({word:"garment", definition:"article of clothing"})
			wordlist.addItem({word:"garner", definition:"to gather and save to store up"})
			wordlist.addItem({word:"garrulity", definition:"talkativeness"})
			wordlist.addItem({word:"garrulous", definition:"too talkative"})
			wordlist.addItem({word:"gaucherie", definition:"socially awkward tactless behavior"})
			wordlist.addItem({word:"germane", definition:"relevant pertinent to"})
			wordlist.addItem({word:"gist", definition:"the point general sense"})
			wordlist.addItem({word:"glean", definition:"gather facts in small quantities"})
			wordlist.addItem({word:"glib", definition:"ready and smooth but not sincere"})
			wordlist.addItem({word:"glimmer", definition:"weak/unsteady light"})
			wordlist.addItem({word:"gloat", definition:"over look at with selfish delight"})
			wordlist.addItem({word:"glut", definition:"supply to much fill to excess"})
			wordlist.addItem({word:"gnaw", definition:"waste away bite steadily"})
			wordlist.addItem({word:"goad", definition:"smth urging a person to action"})
			wordlist.addItem({word:"gorge", definition:"eat greedily/narrow opening with a stream"})
			wordlist.addItem({word:"gossamer", definition:"soft light delicate material"})
			wordlist.addItem({word:"gouge", definition:"tool for cutting grooves in wood"})
			wordlist.addItem({word:"grandiloquent", definition:"using pompous words"})
			wordlist.addItem({word:"grave", definition:"serious requiring consideration"})
			wordlist.addItem({word:"graze", definition:"touch or scrape lightly in passing"})
			wordlist.addItem({word:"gregarious", definition:"living in societies liking the company"})
			wordlist.addItem({word:"grievous", definition:"causing grief or pain serious dire grave"})
			wordlist.addItem({word:"grovel", definition:"crawl humble oneself"})
			wordlist.addItem({word:"guile", definition:"deceit cunning"})
			wordlist.addItem({word:"gullible", definition:"easily gulled"})
			wordlist.addItem({word:"gush", definition:"burst out suddenly/talk ardently"})
			wordlist.addItem({word:"gust", definition:"outburst of feeling sudden rain wind fire etc."})
			wordlist.addItem({word:"hack", definition:"cut roughly hired horse"})
			wordlist.addItem({word:"halcyon", definition:"calm and peaceful"})
			wordlist.addItem({word:"hallow", definition:"to make holy consecrate"})
			wordlist.addItem({word:"harangue", definition:"a long passionate speech"})
			wordlist.addItem({word:"harbinger", definition:"smth or smb that foretells the coming of"})
			wordlist.addItem({word:"harrow", definition:"to distress create stress or torment"})
			wordlist.addItem({word:"haughty", definition:"arrogant conceited"})
			wordlist.addItem({word:"heed", definition:"attention/give notice to"})
			wordlist.addItem({word:"heinous", definition:"odious (of crime)"})
			wordlist.addItem({word:"heresy", definition:"belief contrary to what is generally accepted"})
			wordlist.addItem({word:"hermetic", definition:"sealed by fusion"})
			wordlist.addItem({word:"heterogeneous", definition:"made up of different kinds"})
			wordlist.addItem({word:"hew", definition:"make by hard work cut (by striking)"})
			wordlist.addItem({word:"highbrow", definition:"(person) with superior tastes"})
			wordlist.addItem({word:"hirsute", definition:"hairy shaggy"})
			wordlist.addItem({word:"hoax", definition:"mischievous trick played on smb for a joke"})
			wordlist.addItem({word:"hoi", definition:"polloi the masses the rabble"})
			wordlist.addItem({word:"hollow", definition:"not soled with hole"})
			wordlist.addItem({word:"holster", definition:"leather case for a pistol"})
			wordlist.addItem({word:"homiletics", definition:"act of preaching"})
			wordlist.addItem({word:"hone", definition:"stone used for sharpening tools"})
			wordlist.addItem({word:"hoodwink", definition:"trick mislead"})
			wordlist.addItem({word:"hospitable", definition:"liking to give hospitality"})
			wordlist.addItem({word:"hubris", definition:"arrogant pride"})
			wordlist.addItem({word:"hush", definition:"make or become silent"})
			wordlist.addItem({word:"husk", definition:"worthless outside part of anything"})
			wordlist.addItem({word:"hypocrisy", definition:"falsely making oneself appear to be good"})
			wordlist.addItem({word:"iconoclast", definition:"person who attacks popular beliefs"})
			wordlist.addItem({word:"idiosyncrasy", definition:"personal mannerism"})
			wordlist.addItem({word:"idolatry", definition:"excessive admiration of"})
			wordlist.addItem({word:"idyll", definition:"a carefree episode or experience"})
			wordlist.addItem({word:"ignoble", definition:"dishonorable common undignified"})
			wordlist.addItem({word:"ignominious", definition:"shameful dishonorable undignified disgraceful"})
			wordlist.addItem({word:"illicit", definition:"unlawful forbidden"})
			wordlist.addItem({word:"imbroglio", definition:"complicated and embarrassing situation"})
			wordlist.addItem({word:"immaculate", definition:"pure faultless"})
			wordlist.addItem({word:"imminent", definition:"likely to come or happen soon"})
			wordlist.addItem({word:"immutable", definition:"that cannot be changed"})
			wordlist.addItem({word:"impair", definition:"worsen diminish in value"})
			wordlist.addItem({word:"impassive", definition:"unmoved feeling no sign of passion"})
			wordlist.addItem({word:"impecunious", definition:"having little or no money"})
			wordlist.addItem({word:"impede", definition:"hinder get in the way of"})
			wordlist.addItem({word:"impediment", definition:"smth that hinders (e.g. stammer)"})
			wordlist.addItem({word:"impending", definition:"imminent being about to happen expected"})
			wordlist.addItem({word:"imperative", definition:"urgent essential"})
			wordlist.addItem({word:"imperious", definition:"commanding haughty arrogant"})
			wordlist.addItem({word:"impermeable", definition:"that cannot be permeated"})
			wordlist.addItem({word:"imperturbable", definition:"calm not capable of being excited"})
			wordlist.addItem({word:"impervious", definition:"not allowing to pass through (of materials)"})
			wordlist.addItem({word:"imperviousness", definition:"haughty arrogant commanding"})
			wordlist.addItem({word:"impetuous", definition:"having sudden energy impulsive thrusting ahead forceful"})
			wordlist.addItem({word:"impiety", definition:"lack of reverence or dutifulness"})
			wordlist.addItem({word:"implacable", definition:"incapable of being placated unpleasable"})
			wordlist.addItem({word:"implicate", definition:"show that smb has a share"})
			wordlist.addItem({word:"implicit", definition:"implied though not plainly expressed"})
			wordlist.addItem({word:"implosion", definition:"collapse bursting inward"})
			wordlist.addItem({word:"importune", definition:"beg urgently solicit (of a prostitute)"})
			wordlist.addItem({word:"imprecation", definition:"an invocation of evil a curse"})
			wordlist.addItem({word:"impromptu", definition:"without preparation"})
			wordlist.addItem({word:"impudent", definition:"rash indiscreet"})
			wordlist.addItem({word:"impugned", definition:"challenged to be doubted"})
			wordlist.addItem({word:"impute", definition:"to attribute to a cause or source ascribe"})
			wordlist.addItem({word:"inadvertent", definition:"not paying proper attention"})
			wordlist.addItem({word:"inane", definition:"silly senseless"})
			wordlist.addItem({word:"inasmuch", definition:"since because"})
			wordlist.addItem({word:"incense", definition:"make angry"})
			wordlist.addItem({word:"incessant", definition:"often repeated continual"})
			wordlist.addItem({word:"inchoate", definition:"not yet fully formed rudimentary elementary"})
			wordlist.addItem({word:"incipient", definition:"beginning"})
			wordlist.addItem({word:"incise", definition:"engrave make a cut in"})
			wordlist.addItem({word:"incite", definition:"stir up rouse"})
			wordlist.addItem({word:"inclined", definition:"directing the mind in a certain direction"})
			wordlist.addItem({word:"incongruous", definition:"out of place not in harmony or agreement"})
			wordlist.addItem({word:"incorrigibility", definition:"cannot be cured or corrected"})
			wordlist.addItem({word:"incredulous", definition:"skeptical unwilling to believe"})
			wordlist.addItem({word:"inculcate", definition:"fix firmly by repetition"})
			wordlist.addItem({word:"incumbents", definition:"official duties"})
			wordlist.addItem({word:"incursion", definition:"a raid a sudden attack"})
			wordlist.addItem({word:"indefatigability", definition:"not easily exhaustible tirelessness"})
			wordlist.addItem({word:"indelible", definition:"that cannot be rubbed out"})
			wordlist.addItem({word:"indigence", definition:"poverty"})
			wordlist.addItem({word:"indigenous", definition:"native"})
			wordlist.addItem({word:"indistinct", definition:"not easily heard seen clearly marked"})
			wordlist.addItem({word:"indolence", definition:"laziness"})
			wordlist.addItem({word:"indomitable", definition:"not easily discouraged or subdued"})
			wordlist.addItem({word:"indulge", definition:"gratify give way to satisfy allow oneself"})
			wordlist.addItem({word:"indulgent", definition:"inclined to indulge"})
			wordlist.addItem({word:"ineffable", definition:"to great to be described in words"})
			wordlist.addItem({word:"ineluctable", definition:"certain inevitable"})
			wordlist.addItem({word:"inept", definition:"unskillful said or done at the wrong time"})
			wordlist.addItem({word:"ineptitude", definition:"quality of being unskillful"})
			wordlist.addItem({word:"inferno", definition:"hell"})
			wordlist.addItem({word:"infuriate", definition:"fill with fury or rage"})
			wordlist.addItem({word:"infuse", definition:"put pour fill"})
			wordlist.addItem({word:"ingenuous", definition:"naive young artless frank honest sincere"})
			wordlist.addItem({word:"ingest", definition:"take in by swallowing"})
			wordlist.addItem({word:"inimical", definition:"harmful or friendly"})
			wordlist.addItem({word:"inimitable", definition:"defying imitation unmatchable"})
			wordlist.addItem({word:"innocuous", definition:"causing no harm"})
			wordlist.addItem({word:"inscrutable", definition:"incapable of being discovered or understood"})
			wordlist.addItem({word:"insensible", definition:"unconscious unresponsive unaffected"})
			wordlist.addItem({word:"insinuate", definition:"suggest unpleasantly make a way for smth gently"})
			wordlist.addItem({word:"insipid", definition:"without taste or flavor"})
			wordlist.addItem({word:"insouciant", definition:"unconcerned carefree"})
			wordlist.addItem({word:"insularity", definition:"narrow-mindedness isolated"})
			wordlist.addItem({word:"insurrection", definition:"rising of people to open resistance to"})
			wordlist.addItem({word:"interdict", definition:"prohibit forbid"})
			wordlist.addItem({word:"interim", definition:"as an installment"})
			wordlist.addItem({word:"intersperse", definition:"place here and there"})
			wordlist.addItem({word:"intransigence", definition:"unwillingness to compromise stubbornness intractability"})
			wordlist.addItem({word:"intransigent", definition:"uncompromising"})
			wordlist.addItem({word:"intrepid", definition:"fearless brave undaunted"})
			wordlist.addItem({word:"introspection", definition:"examining one's own thoughts and feelings"})
			wordlist.addItem({word:"inundate", definition:"flood cover by overflowing"})
			wordlist.addItem({word:"inured", definition:"accustomed to adapted"})
			wordlist.addItem({word:"invective", definition:"abusive language curses"})
			wordlist.addItem({word:"inveigh", definition:"to attack verbally denounce deprecate"})
			wordlist.addItem({word:"inveterate", definition:"deep-rooted. long-established"})
			wordlist.addItem({word:"invincible", definition:"too strong to be defeated"})
			wordlist.addItem({word:"involute", definition:"complex"})
			wordlist.addItem({word:"irascible", definition:"irritable easily angered"})
			wordlist.addItem({word:"irate", definition:"angry"})
			wordlist.addItem({word:"ire", definition:"anger"})
			wordlist.addItem({word:"irksome", definition:"tiresome"})
			wordlist.addItem({word:"irresolute", definition:"hesitating undecided"})
			wordlist.addItem({word:"irrevocable", definition:"final and unalterable"})
			wordlist.addItem({word:"itinerate", definition:"to travel from place to place to peregrinate"})
			wordlist.addItem({word:"jabber", definition:"talk excitedly utter rapidly"})
			wordlist.addItem({word:"jibe", definition:"gibe make fun of"})
			wordlist.addItem({word:"jocular", definition:"meant as a joke"})
			wordlist.addItem({word:"judicious", definition:"sound in judgment wise"})
			wordlist.addItem({word:"knit", definition:"draw together unite firmly"})
			wordlist.addItem({word:"labyrinthine", definition:"to entangle the state of affairs"})
			wordlist.addItem({word:"lachrymose", definition:"causing tears tearful"})
			wordlist.addItem({word:"lackluster", definition:"(of eyes) dull"})
			wordlist.addItem({word:"lament", definition:"show feel great sorrow"})
			wordlist.addItem({word:"lassitude", definition:"weariness tiredness"})
			wordlist.addItem({word:"latent", definition:"present but not yet active developed or visible"})
			wordlist.addItem({word:"laudatory", definition:"expressing or giving praise"})
			wordlist.addItem({word:"lavish", definition:"giving or producing freely liberally or generously"})
			wordlist.addItem({word:"legacy", definition:"smth handed down from ancestors"})
			wordlist.addItem({word:"levee", definition:"formal reception/embankment"})
			wordlist.addItem({word:"levity", definition:"lack of seriousness"})
			wordlist.addItem({word:"libel", definition:"statement that damages reputation"})
			wordlist.addItem({word:"liberality", definition:"free giving generosity"})
			wordlist.addItem({word:"libertine", definition:"immoral person"})
			wordlist.addItem({word:"lien", definition:"legal claim until a debt on it is repaid"})
			wordlist.addItem({word:"limn", definition:"paint portray"})
			wordlist.addItem({word:"limp", definition:"lacking strength walking unevenly"})
			wordlist.addItem({word:"lionize", definition:"treat as a famous person"})
			wordlist.addItem({word:"lithe", definition:"bending twisting"})
			wordlist.addItem({word:"loll", definition:"rest to sit or stand in a lazy way hang (dog's tongue)"})
			wordlist.addItem({word:"lope", definition:"move along with long strides"})
			wordlist.addItem({word:"loquacious", definition:"talkative garrulous"})
			wordlist.addItem({word:"lucubrate", definition:"write in scholarly fashion"})
			wordlist.addItem({word:"luculent", definition:"easily understood lucid clear"})
			wordlist.addItem({word:"lugubrious", definition:"mournful excessively sad"})
			wordlist.addItem({word:"lull", definition:"become quiet or less active"})
			wordlist.addItem({word:"lumber", definition:"move in a clumsy/noisy way"})
			wordlist.addItem({word:"luminary", definition:"star light-giving body"})
			wordlist.addItem({word:"lurk", definition:"be out of view ready to attack"})
			wordlist.addItem({word:"lustrous", definition:"being bright polished"})
			wordlist.addItem({word:"macabre", definition:"gruesome suggesting death"})
			wordlist.addItem({word:"macerate", definition:"make or become soft by soaking in water"})
			wordlist.addItem({word:"machination", definition:"plot scheme (esp. evil)"})
			wordlist.addItem({word:"maladroit", definition:"tactless clumsy"})
			wordlist.addItem({word:"malapropism", definition:"misuse of a word (for one that resembles it)"})
			wordlist.addItem({word:"malevolence", definition:"wishing to do evil"})
			wordlist.addItem({word:"malign", definition:"injurious speak ill of smb tell lie"})
			wordlist.addItem({word:"malinger", definition:"to fake illness or injury in order to shirk a duty"})
			wordlist.addItem({word:"malleable", definition:"yielding easily shaped moldable adapting"})
			wordlist.addItem({word:"manacle", definition:"chains for the hands or feet"})
			wordlist.addItem({word:"massacre", definition:"cruel killing of a large number of people"})
			wordlist.addItem({word:"matriculation", definition:"be admitted enter a university as a student"})
			wordlist.addItem({word:"maudlin", definition:"sentimental in a silly or tearful way"})
			wordlist.addItem({word:"maul", definition:"hurt by rough handling"})
			wordlist.addItem({word:"maverick", definition:"rebel nonconformist"})
			wordlist.addItem({word:"mellifluous", definition:"sweetly flowing"})
			wordlist.addItem({word:"mendacity", definition:"dishonesty"})
			wordlist.addItem({word:"mendicant", definition:"a beggar"})
			wordlist.addItem({word:"mercurial", definition:"quick changeable in character fleeting"})
			wordlist.addItem({word:"meretricious", definition:"attractive on the surface but of little value"})
			wordlist.addItem({word:"mesmerize", definition:"hypnotize"})
			wordlist.addItem({word:"meticulous", definition:"giving great attention to details"})
			wordlist.addItem({word:"mettle", definition:"quality of endurance or courage"})
			wordlist.addItem({word:"mettlesome", definition:"courageous high-spirited"})
			wordlist.addItem({word:"middling", definition:"fairly good but not very good"})
			wordlist.addItem({word:"minatory", definition:"menacing threatening"})
			wordlist.addItem({word:"mince", definition:"pronounce or speak affectedly euphemize"})
			wordlist.addItem({word:"misanthrope", definition:"person who hates mankind"})
			wordlist.addItem({word:"mischievous", definition:"harmful causing mischief"})
			wordlist.addItem({word:"miser", definition:"person who loves wealth and spends little"})
			wordlist.addItem({word:"misogynist", definition:"one who hates women/females"})
			wordlist.addItem({word:"moderation", definition:"quality of being limited not extreme"})
			wordlist.addItem({word:"mollify", definition:"make calmer or quieter"})
			wordlist.addItem({word:"molt", definition:"moult lose hair feathers before new growing"})
			wordlist.addItem({word:"morbid", definition:"diseased unhealthy (e.g.. about ideas)"})
			wordlist.addItem({word:"morose", definition:"ill-tempered unsocial"})
			wordlist.addItem({word:"muffler", definition:"cloth worn round the neck/silencer"})
			wordlist.addItem({word:"multifarious", definition:"varied motley greatly diversified"})
			wordlist.addItem({word:"mundane", definition:"worldly as opposed to spiritual commonplace everyday"})
			wordlist.addItem({word:"myriad", definition:"very great number"})
			wordlist.addItem({word:"nadir", definition:"lowest weakest point"})
			wordlist.addItem({word:"nascent", definition:"coming into existence emerging"})
			wordlist.addItem({word:"nebulous", definition:"cloud-like hazy vague indistinct"})
			wordlist.addItem({word:"negligent", definition:"taking too little care"})
			wordlist.addItem({word:"neophyte", definition:"person who has been converted to a belief"})
			wordlist.addItem({word:"nexus", definition:"a connection tie or link"})
			wordlist.addItem({word:"nibble", definition:"show some inclination to accept (an offer)"})
			wordlist.addItem({word:"noisome", definition:"offensive disgusting (smell)"})
			wordlist.addItem({word:"nonchalant", definition:"not having interest"})
			wordlist.addItem({word:"nonplused", definition:"greatly surprised"})
			wordlist.addItem({word:"nostrum", definition:"a quack remedy an untested cure"})
			wordlist.addItem({word:"noxious", definition:"harmful"})
			wordlist.addItem({word:"nugatory", definition:"trifling/worthless"})
			wordlist.addItem({word:"obdurate", definition:"hardened and unrepenting stubborn inflexible"})
			wordlist.addItem({word:"obfuscate", definition:"to darken make obscure muddle"})
			wordlist.addItem({word:"oblivious", definition:"unaware having no memory"})
			wordlist.addItem({word:"obloquy", definition:"abusively detractive language sharp criticism vituperation"})
			wordlist.addItem({word:"obsequious", definition:"too eager to obey or serve"})
			wordlist.addItem({word:"obstreperous", definition:"noisy loud"})
			wordlist.addItem({word:"obtain", definition:"to be established accepted or customary"})
			wordlist.addItem({word:"obtrusive", definition:"projecting prominent undesirably noticeable"})
			wordlist.addItem({word:"obtuse", definition:"blunt/stupid"})
			wordlist.addItem({word:"obviate", definition:"to make unnecessary get rid of"})
			wordlist.addItem({word:"occluded", definition:"blocked up"})
			wordlist.addItem({word:"odious", definition:"repulsive hateful"})
			wordlist.addItem({word:"odium", definition:"contempt dislike aversion"})
			wordlist.addItem({word:"odor", definition:"smell favor reputation"})
			wordlist.addItem({word:"officious", definition:"too eager or ready to help offer advice"})
			wordlist.addItem({word:"ominous", definition:"threatening"})
			wordlist.addItem({word:"onerous", definition:"needing effort burdensome"})
			wordlist.addItem({word:"opaqueness", definition:"dullness/not allowing light to pass through"})
			wordlist.addItem({word:"opprobrious", definition:"showing scorn or reproach"})
			wordlist.addItem({word:"ossify", definition:"to turn to bone to settle rigidly into an idea"})
			wordlist.addItem({word:"ostensible", definition:"seeming appearing as such professed"})
			wordlist.addItem({word:"ostentation", definition:"display to obtain admiration or envy"})
			wordlist.addItem({word:"ostracism", definition:"shut out from society refuse to meet talk"})
			wordlist.addItem({word:"overhaul", definition:"examine thoroughly to learn about the condition"})
			wordlist.addItem({word:"overweening", definition:"presumptuously arrogant overbearing immoderate being a jerk"})
			wordlist.addItem({word:"paean", definition:"song of praise or triumph"})
			wordlist.addItem({word:"palate", definition:"roof of the mouth sense of taste"})
			wordlist.addItem({word:"palatial", definition:"magnificent"})
			wordlist.addItem({word:"palliate", definition:"lessen the severity of"})
			wordlist.addItem({word:"palpability", definition:"can be felt touched understood"})
			wordlist.addItem({word:"palpitate", definition:"tremble beat rapidly and irregularly"})
			wordlist.addItem({word:"panegyric", definition:"formal praise eulogy"})
			wordlist.addItem({word:"paradigm", definition:"a model example or pattern"})
			wordlist.addItem({word:"parenthesis", definition:"sentence within another one smth separated"})
			wordlist.addItem({word:"pariah", definition:"an outcast a rejected and despised person"})
			wordlist.addItem({word:"parsimonious", definition:"too economical miserly"})
			wordlist.addItem({word:"partisan", definition:"one-sided committed to a party biased or prejudiced"})
			wordlist.addItem({word:"patron", definition:"regular customer person who gives support"})
			wordlist.addItem({word:"paucity", definition:"scarcity a lacking of"})
			wordlist.addItem({word:"peccadillo", definition:"small sin small weakness in one's character"})
			wordlist.addItem({word:"pedantic", definition:"bookish showing off learning"})
			wordlist.addItem({word:"pedestrian", definition:"commonplace trite unremarkable"})
			wordlist.addItem({word:"pellucid", definition:"transparent easy to understand"})
			wordlist.addItem({word:"penchant", definition:"strong inclination a liking"})
			wordlist.addItem({word:"penitent", definition:"feeling or showing regret"})
			wordlist.addItem({word:"penurious", definition:"poor/stingy"})
			wordlist.addItem({word:"penury", definition:"extreme poverty"})
			wordlist.addItem({word:"peregrination", definition:"traveling about wandering"})
			wordlist.addItem({word:"peremptory", definition:"urgent imperative unchallengeable ending debate"})
			wordlist.addItem({word:"perfidious", definition:"treacherous faithless"})
			wordlist.addItem({word:"perfidy", definition:"treachery breaking of faith"})
			wordlist.addItem({word:"perfunctory", definition:"done as a duty without care"})
			wordlist.addItem({word:"perilous", definition:"dangerous"})
			wordlist.addItem({word:"peripatetic", definition:"wandering"})
			wordlist.addItem({word:"perish", definition:"be destroyed decay"})
			wordlist.addItem({word:"perjury", definition:"willful FALSE statement unlawful act"})
			wordlist.addItem({word:"permeate", definition:"spread into every part of"})
			wordlist.addItem({word:"pernicious", definition:"harmful injurious"})
			wordlist.addItem({word:"perpetrate", definition:"be guilty commit (a crime)"})
			wordlist.addItem({word:"personable", definition:"pleasing in appearance attractive"})
			wordlist.addItem({word:"perspicacity", definition:"quick judging and understanding"})
			wordlist.addItem({word:"pertain", definition:"belong as a part have reference"})
			wordlist.addItem({word:"pest", definition:"destructive thing or a person who is nuisance"})
			wordlist.addItem({word:"petrified", definition:"taken away power (to think feel act)"})
			wordlist.addItem({word:"petrify", definition:"to make hard rocklike"})
			wordlist.addItem({word:"petrous", definition:"like a rock hard stony"})
			wordlist.addItem({word:"petulant", definition:"unreasonably impatient"})
			wordlist.addItem({word:"philistine", definition:"a smug ignorant person one who lacks knowledge"})
			wordlist.addItem({word:"phlegmatic", definition:"calm sluggish temperament unemotional"})
			wordlist.addItem({word:"picaresque", definition:"involving clever rogues or adventurers"})
			wordlist.addItem({word:"pied", definition:"of mixed colors"})
			wordlist.addItem({word:"pinch", definition:"be too tight take between the thumb and finger"})
			wordlist.addItem({word:"pine", definition:"waste away through sorrow or illness"})
			wordlist.addItem({word:"pious", definition:"dutiful to parents devoted to religion"})
			wordlist.addItem({word:"piquant", definition:"agreeably pungent stimulating"})
			wordlist.addItem({word:"pique", definition:"hurt the pride or self-respect stir (curiosity)"})
			wordlist.addItem({word:"pitfall", definition:"covered hole as a trap unsuspected danger"})
			wordlist.addItem({word:"pith", definition:"essential part force soft liquid substance"})
			wordlist.addItem({word:"pivotal", definition:"of great importance (others depend on it)"})
			wordlist.addItem({word:"placate", definition:"soothe pacify calm"})
			wordlist.addItem({word:"plaintive", definition:"mournful melancholy sorrowful"})
			wordlist.addItem({word:"plaque", definition:"flat metal on a wall as a memorial"})
			wordlist.addItem({word:"platitude", definition:"a trite or banal statement unoriginality"})
			wordlist.addItem({word:"plea", definition:"request"})
			wordlist.addItem({word:"plead", definition:"address a court of law as an advocate"})
			wordlist.addItem({word:"plethora", definition:"glut"})
			wordlist.addItem({word:"pliant", definition:"pliable easily bent shaped or twisted"})
			wordlist.addItem({word:"plod", definition:"continue doing smth without resting"})
			wordlist.addItem({word:"pluck", definition:"pull the feathers off pick (e.g.. flowers)"})
			wordlist.addItem({word:"plumb", definition:"get to the root of"})
			wordlist.addItem({word:"plummet", definition:"fall plunge steeply"})
			wordlist.addItem({word:"plunge", definition:"move quickly suddenly and with force"})
			wordlist.addItem({word:"poignant", definition:"deeply moving keen"})
			wordlist.addItem({word:"poncho", definition:"large piece of cloth"})
			wordlist.addItem({word:"ponderous", definition:"heavy bulky dull"})
			wordlist.addItem({word:"portent", definition:"omen marvelous threatening"})
			wordlist.addItem({word:"precarious", definition:"uncertain risky dangerous"})
			wordlist.addItem({word:"precepts", definition:"rules establishing standards of conduct"})
			wordlist.addItem({word:"preclude", definition:"prevent make impossible"})
			wordlist.addItem({word:"precursory", definition:"preliminary anticipating"})
			wordlist.addItem({word:"predilection", definition:"special liking mental preference"})
			wordlist.addItem({word:"predominate", definition:"have more power than others"})
			wordlist.addItem({word:"preen", definition:"tidy/show self-satisfaction"})
			wordlist.addItem({word:"premature", definition:"doing or happening smth before the right time"})
			wordlist.addItem({word:"preponderance", definition:"greatness in number strength weight"})
			wordlist.addItem({word:"presage", definition:"warning sign"})
			wordlist.addItem({word:"presumption", definition:"arrogance"})
			wordlist.addItem({word:"preternatural", definition:"not normal or usual"})
			wordlist.addItem({word:"prevalent", definition:"common"})
			wordlist.addItem({word:"prevaricate", definition:"to equivocate to stray from the truth"})
			wordlist.addItem({word:"prim", definition:"neat formal"})
			wordlist.addItem({word:"pristine", definition:"primitive unspoiled pure as in earlier times unadulterated"})
			wordlist.addItem({word:"probity", definition:"uprightness incorruptibility principle"})
			wordlist.addItem({word:"proclivity", definition:"inclination"})
			wordlist.addItem({word:"procrastination", definition:"keeping on putting off"})
			wordlist.addItem({word:"prodigal", definition:"wasteful reckless with money"})
			wordlist.addItem({word:"prodigious", definition:"enormous wonderful"})
			wordlist.addItem({word:"profane", definition:"worldly having contempt for God"})
			wordlist.addItem({word:"profligacy", definition:"shameless immorality"})
			wordlist.addItem({word:"profligate", definition:"wasteful prodigal licentious extravagant"})
			wordlist.addItem({word:"profundity", definition:"depth"})
			wordlist.addItem({word:"profuse", definition:"abundant/lavish"})
			wordlist.addItem({word:"proliferate", definition:"grow reproduce by rapid multification"})
			wordlist.addItem({word:"prolix", definition:"tiring because too long"})
			wordlist.addItem({word:"prone", definition:"prostrate inclined to (undesirable things)"})
			wordlist.addItem({word:"propagation", definition:"increasing the number spreading extending"})
			wordlist.addItem({word:"propinquity", definition:"nearness in time or place affinity of nature"})
			wordlist.addItem({word:"propitiatory", definition:"conciliatory appeasing mitigating"})
			wordlist.addItem({word:"propitious", definition:"auspicious presenting favorable circumstances"})
			wordlist.addItem({word:"prosaic", definition:"everyday mundane commonplace trite pedestrian"})
			wordlist.addItem({word:"proscribe", definition:"denounce as dangerous"})
			wordlist.addItem({word:"protracted", definition:"prolonged"})
			wordlist.addItem({word:"provident", definition:"frugal looking to the future"})
			wordlist.addItem({word:"provisional", definition:"of the present time only"})
			wordlist.addItem({word:"provoke", definition:"make angry vax"})
			wordlist.addItem({word:"prudence", definition:"careful forethought"})
			wordlist.addItem({word:"prudish", definition:"easily shocked excessively modest"})
			wordlist.addItem({word:"prune", definition:"dried plum silly person"})
			wordlist.addItem({word:"pry", definition:"get smth inquire too curiously"})
			wordlist.addItem({word:"pucker", definition:"wrinkle"})
			wordlist.addItem({word:"pugnacious", definition:"fond of in the habit of fighting"})
			wordlist.addItem({word:"puissance", definition:"strength"})
			wordlist.addItem({word:"punctilious", definition:"precise paying attention to trivialities"})
			wordlist.addItem({word:"pundit", definition:"pedant authority on a subject"})
			wordlist.addItem({word:"pungency", definition:"sharpness stinging quality"})
			wordlist.addItem({word:"purvey", definition:"provide supply"})
			wordlist.addItem({word:"pusillanimous", definition:"cowardly craven"})
			wordlist.addItem({word:"putrefaction", definition:"becoming rotten"})
			wordlist.addItem({word:"pyre", definition:"large pile of wood for burning"})
			wordlist.addItem({word:"quack", definition:"person dishonestly claiming to smth"})
			wordlist.addItem({word:"quaff", definition:"drink deeply"})
			wordlist.addItem({word:"quail", definition:"lose courage turn frightened"})
			wordlist.addItem({word:"qualm", definition:"feeling of doubt temporary feeling of sickness"})
			wordlist.addItem({word:"quandary", definition:"state of doubt or perplexity"})
			wordlist.addItem({word:"quell", definition:"suppress subdue"})
			wordlist.addItem({word:"quibble", definition:"try to avoid by sophistication"})
			wordlist.addItem({word:"quiescence", definition:"state of being passive/motionless"})
			wordlist.addItem({word:"quiescent", definition:"at rest dormant torpid"})
			wordlist.addItem({word:"quirk", definition:"habit or action peculiar to smb or smth"})
			wordlist.addItem({word:"quixotic", definition:"generous unselfish"})
			wordlist.addItem({word:"quotidian", definition:"banal everyday"})
			wordlist.addItem({word:"rabble", definition:"mob crowd the lower classes of populace"})
			wordlist.addItem({word:"raconteur", definition:"person who tells anecdotes"})
			wordlist.addItem({word:"raffish", definition:"low vulgar base tawdry"})
			wordlist.addItem({word:"ramify", definition:"to be divided or subdivided to branch out"})
			wordlist.addItem({word:"rancorous", definition:"feeling bitterness spitefulness"})
			wordlist.addItem({word:"rant", definition:"use extravagant language"})
			wordlist.addItem({word:"rapacious", definition:"greedy (esp for money)"})
			wordlist.addItem({word:"rarefy", definition:"to make thin to make less dense to purify or refine"})
			wordlist.addItem({word:"rave", definition:"act with excessive enthusiasm"})
			wordlist.addItem({word:"reactionary", definition:"opposing progress"})
			wordlist.addItem({word:"rebuff", definition:"snub"})
			wordlist.addItem({word:"recalcitrant", definition:"disobedient"})
			wordlist.addItem({word:"recant", definition:"take back as being FALSE give up"})
			wordlist.addItem({word:"recast", definition:"cast or fashion anew"})
			wordlist.addItem({word:"recidivism", definition:"relapse into antisocial or criminal behavior"})
			wordlist.addItem({word:"reciprocity", definition:"granting of privileges in return for similar"})
			wordlist.addItem({word:"recitals", definition:"a number of performance of music"})
			wordlist.addItem({word:"recluse", definition:"person who lives alone and avoids people"})
			wordlist.addItem({word:"recompense", definition:"make payment to reward punish"})
			wordlist.addItem({word:"reconcile", definition:"settle a quarrel restore peace"})
			wordlist.addItem({word:"recondite", definition:"little known abstruse"})
			wordlist.addItem({word:"recreancy", definition:"cowardice a cowardly giving up"})
			wordlist.addItem({word:"recuperate", definition:"become strong after illness loss exhaustion"})
			wordlist.addItem({word:"redeem", definition:"get back by payment compensate"})
			wordlist.addItem({word:"redoubtable", definition:"formidable causing fear"})
			wordlist.addItem({word:"refine", definition:"make or become pure cultural"})
			wordlist.addItem({word:"refractory", definition:"stubborn unmanageable untractable"})
			wordlist.addItem({word:"refulgent", definition:"shining brilliant"})
			wordlist.addItem({word:"regale", definition:"to delight or entertain to feast"})
			wordlist.addItem({word:"regicide", definition:"crime of killing a king"})
			wordlist.addItem({word:"reiterate", definition:"say or do again several times"})
			wordlist.addItem({word:"rejuvenation", definition:"becoming young in nature or appearance"})
			wordlist.addItem({word:"relapse", definition:"fall back again"})
			wordlist.addItem({word:"remonstrate", definition:"to protest object"})
			wordlist.addItem({word:"render", definition:"deliver provide represent"})
			wordlist.addItem({word:"renovate", definition:"restore smth to better condition"})
			wordlist.addItem({word:"renowned", definition:"celebrated famous"})
			wordlist.addItem({word:"repast", definition:"meal"})
			wordlist.addItem({word:"repel", definition:"refuse to accept/cause dislike"})
			wordlist.addItem({word:"repine", definition:"at be discontented with"})
			wordlist.addItem({word:"reproach", definition:"scold upbraid"})
			wordlist.addItem({word:"reprobate", definition:"person hardened in sin one devoid of decency"})
			wordlist.addItem({word:"repudiate", definition:"disown refuse to accept or pay"})
			wordlist.addItem({word:"repulsive", definition:"causing a feeling of disgust"})
			wordlist.addItem({word:"requite", definition:"repay give in return"})
			wordlist.addItem({word:"rescind", definition:"repeal/annul/cancel"})
			wordlist.addItem({word:"resigned", definition:"unresisting submissive"})
			wordlist.addItem({word:"resilience", definition:"quality of quickly recovering the original shape"})
			wordlist.addItem({word:"resort", definition:"to frequently visit"})
			wordlist.addItem({word:"restive", definition:"refusing to move reluctant to be controlled"})
			wordlist.addItem({word:"resuscitation", definition:"coming back to consciousness"})
			wordlist.addItem({word:"retard", definition:"check hinder"})
			wordlist.addItem({word:"reticent", definition:"reserved untalkative silent taciturn"})
			wordlist.addItem({word:"revere", definition:"have deep respect for"})
			wordlist.addItem({word:"reverent", definition:"feeling or showing deep respect"})
			wordlist.addItem({word:"riddle", definition:"puzzling person or thing"})
			wordlist.addItem({word:"rift", definition:"split crack dissension"})
			wordlist.addItem({word:"rivet", definition:"fix take up secure metal pin"})
			wordlist.addItem({word:"roll", definition:"call calling of names"})
			wordlist.addItem({word:"rotund", definition:"rich and deep plump and round"})
			wordlist.addItem({word:"ruffian", definition:"violent cruel man"})
			wordlist.addItem({word:"rumple", definition:"make rough"})
			wordlist.addItem({word:"sagacious", definition:"having sound judgment perceptive wise like a sage"})
			wordlist.addItem({word:"salacious", definition:"obscene"})
			wordlist.addItem({word:"salubrious", definition:"healthful"})
			wordlist.addItem({word:"salutary", definition:"remedial wholesome causing improvement"})
			wordlist.addItem({word:"sanctimony", definition:"self-righteousness hypocritical with FALSE piety"})
			wordlist.addItem({word:"sanction", definition:"approval (by authority) penalty"})
			wordlist.addItem({word:"sanguine", definition:"cheerful confident optimistic"})
			wordlist.addItem({word:"sanity", definition:"health of mind soundness of judgement"})
			wordlist.addItem({word:"sash", definition:"long strip worn round the waist"})
			wordlist.addItem({word:"satiate", definition:"satisfy fully"})
			wordlist.addItem({word:"saturnine", definition:"gloomy dark sullen morose"})
			wordlist.addItem({word:"savant", definition:"person of great learning"})
			wordlist.addItem({word:"savor", definition:"taste flavor smth"})
			wordlist.addItem({word:"sawdust", definition:"tiny bits of wood"})
			wordlist.addItem({word:"scabbard", definition:"sheath for the blade"})
			wordlist.addItem({word:"scent", definition:"smell (esp pleasant)"})
			wordlist.addItem({word:"scorch", definition:"become discolored/dry up/go at high speed"})
			wordlist.addItem({word:"scribble", definition:"write hastily"})
			wordlist.addItem({word:"scurvy", definition:"mean contemptible"})
			wordlist.addItem({word:"secular", definition:"material (not spiritual) living outside monasteries"})
			wordlist.addItem({word:"sedulous", definition:"persevering"})
			wordlist.addItem({word:"seminal", definition:"like a seed constituting a source originative"})
			wordlist.addItem({word:"sententious", definition:"short and pithy full of maxims/proverbs"})
			wordlist.addItem({word:"sequence", definition:"succession connected line of"})
			wordlist.addItem({word:"sere", definition:"make hard and without feeling"})
			wordlist.addItem({word:"sermon", definition:"reproving a person for his faults"})
			wordlist.addItem({word:"serrated", definition:"having a toothed edge"})
			wordlist.addItem({word:"serration", definition:"having a toothed edge"})
			wordlist.addItem({word:"servile", definition:"like a slave lacking independence"})
			wordlist.addItem({word:"sever", definition:"break off"})
			wordlist.addItem({word:"severance", definition:"severing"})
			wordlist.addItem({word:"shallow", definition:"little depth not earnest"})
			wordlist.addItem({word:"shard", definition:"piece of broken earthenware"})
			wordlist.addItem({word:"sheath", definition:"cover for the blade of a weapon or a tool"})
			wordlist.addItem({word:"shrewd", definition:"astute showing sound judgement"})
			wordlist.addItem({word:"shrill", definition:"sharp piercing"})
			wordlist.addItem({word:"shun", definition:"keep away from avoid"})
			wordlist.addItem({word:"shunt", definition:"send from one track to another lay aside evade discussion"})
			wordlist.addItem({word:"sidestep", definition:"step to one side"})
			wordlist.addItem({word:"simper", definition:"(give a) silly/self-conscious smile"})
			wordlist.addItem({word:"sinuous", definition:"winding undulating serpentine"})
			wordlist.addItem({word:"skiff", definition:"small boat"})
			wordlist.addItem({word:"skit", definition:"short piece of humorous writing"})
			wordlist.addItem({word:"slack", definition:"sluggish dull not tight"})
			wordlist.addItem({word:"slake", definition:"to assuage to satisfy allay"})
			wordlist.addItem({word:"slate", definition:"king of blue-grey stone propose criticize"})
			wordlist.addItem({word:"sluggard", definition:"lazy slow-moving person"})
			wordlist.addItem({word:"slur", definition:"join sounds/words (indistinct)"})
			wordlist.addItem({word:"smolder", definition:"burn slowly without flame"})
			wordlist.addItem({word:"snare", definition:"trap"})
			wordlist.addItem({word:"snub", definition:"treat with contempt"})
			wordlist.addItem({word:"soar", definition:"rise fly high"})
			wordlist.addItem({word:"sober", definition:"self-controlled"})
			wordlist.addItem({word:"sobriety", definition:"quality or condition of being sober"})
			wordlist.addItem({word:"sodden", definition:"soaked saturated"})
			wordlist.addItem({word:"soggy", definition:"heavy with water"})
			wordlist.addItem({word:"solvent", definition:"of the power of forming a solution"})
			wordlist.addItem({word:"somatic", definition:"of the body"})
			wordlist.addItem({word:"soot", definition:"black powder in smoke"})
			wordlist.addItem({word:"sophisticated", definition:"complex subtle refined"})
			wordlist.addItem({word:"sophistry", definition:"fallacious reasoning faulty logic"})
			wordlist.addItem({word:"sophomoric", definition:"self-assured though immature affected bombastic overblown"})
			wordlist.addItem({word:"soporific", definition:"producing sleep"})
			wordlist.addItem({word:"sordid", definition:"wretched comfortless contemptible"})
			wordlist.addItem({word:"spear", definition:"weapon with a metal point on a long shaft"})
			wordlist.addItem({word:"specious", definition:"illogical of questionable truth or merit"})
			wordlist.addItem({word:"splenetic", definition:"bad-tempered irritable"})
			wordlist.addItem({word:"splice", definition:"join (two ends)"})
			wordlist.addItem({word:"sponge", definition:"porous rubber for washing live at once expense"})
			wordlist.addItem({word:"spurious", definition:"FALSE counterfeit"})
			wordlist.addItem({word:"spurn", definition:"have nothing to do reject or refuse"})
			wordlist.addItem({word:"squalid", definition:"foul filthy"})
			wordlist.addItem({word:"squander", definition:"spend wastefully"})
			wordlist.addItem({word:"squat", definition:"crouch/settle without permission"})
			wordlist.addItem({word:"stanch", definition:"to stop the flow of a fluid"})
			wordlist.addItem({word:"steeply", definition:"rising or falling sharply"})
			wordlist.addItem({word:"stentorian", definition:"extremely loud and powerful"})
			wordlist.addItem({word:"stickler", definition:"person who insists on importance of smth"})
			wordlist.addItem({word:"stigma", definition:"mark of shame or disgrace"})
			wordlist.addItem({word:"stigmatize", definition:"describe smb scornfully"})
			wordlist.addItem({word:"sting", definition:"smth sharp"})
			wordlist.addItem({word:"stingy", definition:"spending using unwillingly"})
			wordlist.addItem({word:"stint", definition:"to be thrifty to set limits"})
			wordlist.addItem({word:"stipple", definition:"paint with dots"})
			wordlist.addItem({word:"stipulate", definition:"state or put forward as a necessary condition"})
			wordlist.addItem({word:"stolid", definition:"showing no emotion impassive"})
			wordlist.addItem({word:"stray", definition:"wander lose one's way"})
			wordlist.addItem({word:"streak", definition:"long thin move very fast"})
			wordlist.addItem({word:"striated", definition:"striped grooved or banded"})
			wordlist.addItem({word:"stride", definition:"walk with long steps"})
			wordlist.addItem({word:"strut", definition:"a supporting bar"})
			wordlist.addItem({word:"stygian", definition:"hence dark gloomy"})
			wordlist.addItem({word:"stymie", definition:"to hinder obstruct or block"})
			wordlist.addItem({word:"subdue", definition:"overcome bring under control"})
			wordlist.addItem({word:"sublime", definition:"extreme astounding"})
			wordlist.addItem({word:"submerge", definition:"put under water liquid sink out of sight"})
			wordlist.addItem({word:"suborn", definition:"induce by bribery or smth to commit perjury"})
			wordlist.addItem({word:"subpoena", definition:"written order requiring a person to appear in a low court"})
			wordlist.addItem({word:"substantiation", definition:"giving facts to support (statement)"})
			wordlist.addItem({word:"subsume", definition:"include under a rule"})
			wordlist.addItem({word:"succor", definition:"assistance relief in time of distress"})
			wordlist.addItem({word:"suffice", definition:"be enough"})
			wordlist.addItem({word:"suffocate", definition:"cause or have difficulty in breathing"})
			wordlist.addItem({word:"sullied", definition:"to be stained or discredited"})
			wordlist.addItem({word:"summarily", definition:"briefly without delay"})
			wordlist.addItem({word:"sumptuous", definition:"magnificent"})
			wordlist.addItem({word:"sundry", definition:"various miscellaneous separate"})
			wordlist.addItem({word:"supercilious", definition:"disdainful characterized by haughty scorn"})
			wordlist.addItem({word:"superfluous", definition:"more then is needed or wanted"})
			wordlist.addItem({word:"superimpose", definition:"put smth on the top"})
			wordlist.addItem({word:"supersede", definition:"take the place of"})
			wordlist.addItem({word:"supine", definition:"lying on the back slow to act passive"})
			wordlist.addItem({word:"suppliant", definition:"asking humbly beseeching"})
			wordlist.addItem({word:"supplicate", definition:"make a humble petition to"})
			wordlist.addItem({word:"suppress", definition:"prevent from being known put an end to"})
			wordlist.addItem({word:"surcharge", definition:"additional load/charge"})
			wordlist.addItem({word:"surfeit", definition:"satiate feed to fulness or to excess"})
			wordlist.addItem({word:"susceptibility", definition:"sensitiveness"})
			wordlist.addItem({word:"swerve", definition:"change direction suddenly"})
			wordlist.addItem({word:"sycophant", definition:"person who flatter to the rich and powerful"})
			wordlist.addItem({word:"synopsis", definition:"summary or outline"})
			wordlist.addItem({word:"taciturn", definition:"untalkative silent"})
			wordlist.addItem({word:"tadpole", definition:"form of a frog when it leaves the egg"})
			wordlist.addItem({word:"talon", definition:"claw of a bird of prey"})
			wordlist.addItem({word:"tamp", definition:"tap or drive down by repeated light blows"})
			wordlist.addItem({word:"tamper", definition:"interfere with"})
			wordlist.addItem({word:"tangential", definition:"suddenly changeable"})
			wordlist.addItem({word:"tarnished", definition:"lost brightness"})
			wordlist.addItem({word:"tassel", definition:"bunch of threads"})
			wordlist.addItem({word:"taunt", definition:"contemptuous reproach hurtful remark"})
			wordlist.addItem({word:"taut", definition:"tightly stretched"})
			wordlist.addItem({word:"tautology", definition:"a repetition a redundancy"})
			wordlist.addItem({word:"tawdry", definition:"cheap gaudy showy tacky"})
			wordlist.addItem({word:"teetotal", definition:"oppose to alcohol"})
			wordlist.addItem({word:"temerity", definition:"boldness brashness intrepidness"})
			wordlist.addItem({word:"temperance", definition:"abstinence from alcohol self-control moderation"})
			wordlist.addItem({word:"temperate", definition:"showing self-control"})
			wordlist.addItem({word:"tenacity", definition:"firmness persistency adhesiveness tending to hang on"})
			wordlist.addItem({word:"tenuous", definition:"insubstantial flimsy weak"})
			wordlist.addItem({word:"tepid", definition:"lukewarm"})
			wordlist.addItem({word:"terse", definition:"brief and to the point"})
			wordlist.addItem({word:"testiness", definition:"witness/evidence"})
			wordlist.addItem({word:"thrift", definition:"care economy thriving prosperous"})
			wordlist.addItem({word:"thwart", definition:"obstruct/frustrate"})
			wordlist.addItem({word:"timid", definition:"shy easily frightened"})
			wordlist.addItem({word:"timorous", definition:"fearful timid afraid"})
			wordlist.addItem({word:"toady", definition:"obsequious flatterer"})
			wordlist.addItem({word:"tonic", definition:"smth giving strength or energy"})
			wordlist.addItem({word:"topple", definition:"be unsteady and overturn"})
			wordlist.addItem({word:"torment", definition:"severe pain or suffering"})
			wordlist.addItem({word:"torpid", definition:"sleeping sluggish lethargic dormant"})
			wordlist.addItem({word:"torque", definition:"twisting force causing rotation"})
			wordlist.addItem({word:"tortuous", definition:"devious/not straightforward"})
			wordlist.addItem({word:"tout", definition:"person who worries others to buy smth to use his service"})
			wordlist.addItem({word:"tractable", definition:"easily controlled or guided"})
			wordlist.addItem({word:"transgress", definition:"break go beyond (a limit)"})
			wordlist.addItem({word:"transient", definition:"temporary fleeting"})
			wordlist.addItem({word:"transitory", definition:"brief"})
			wordlist.addItem({word:"travesty", definition:"parody/imitation"})
			wordlist.addItem({word:"trenchant", definition:"forceful effective vigorous extremely perceptive incisive"})
			wordlist.addItem({word:"trepidation", definition:"alarm excited state of mind"})
			wordlist.addItem({word:"trickle", definition:"flow in drops"})
			wordlist.addItem({word:"trifling", definition:"unimportant"})
			wordlist.addItem({word:"trite", definition:"not new"})
			wordlist.addItem({word:"truce", definition:"(agreement) stop of fighting for a time"})
			wordlist.addItem({word:"truculence", definition:"aggressiveness ferocity"})
			wordlist.addItem({word:"trudge", definition:"walk heavily"})
			wordlist.addItem({word:"turbid", definition:"muddy having the sediment stirred up"})
			wordlist.addItem({word:"turbulence", definition:"being uncontrolled violent"})
			wordlist.addItem({word:"turgid", definition:"excessively ornate swollen or bloated"})
			wordlist.addItem({word:"turmoil", definition:"trouble disturbance"})
			wordlist.addItem({word:"turpitude", definition:"wickedness shamefulness"})
			wordlist.addItem({word:"turquoise", definition:"greenish-blue precious stone"})
			wordlist.addItem({word:"tyro", definition:"tiro beginner"})
			wordlist.addItem({word:"ubiquitous", definition:"present everywhere"})
			wordlist.addItem({word:"ulterior", definition:"situated beyond"})
			wordlist.addItem({word:"umbrage", definition:"offense resentment"})
			wordlist.addItem({word:"uncouth", definition:"rough awkward"})
			wordlist.addItem({word:"underbid", definition:"make a lower bid then smb else"})
			wordlist.addItem({word:"undermine", definition:"weaken gradually at the base make smth under"})
			wordlist.addItem({word:"undulate", definition:"to move in wavelike fashion fluctuate"})
			wordlist.addItem({word:"unearth", definition:"discover and bring to light"})
			wordlist.addItem({word:"unencumbered", definition:"easy-going trifle"})
			wordlist.addItem({word:"unfeigned", definition:"not pretended sincere"})
			wordlist.addItem({word:"unscathed", definition:"unharmed unhurt"})
			wordlist.addItem({word:"untoward", definition:"unfortunate inconvenient"})
			wordlist.addItem({word:"upbraid", definition:"scold reproach"})
			wordlist.addItem({word:"urbane", definition:"elegant refined in manners"})
			wordlist.addItem({word:"vacillation", definition:"being uncertain hesitating"})
			wordlist.addItem({word:"vagary", definition:"strange act or idea"})
			wordlist.addItem({word:"vain", definition:"without use result conceited"})
			wordlist.addItem({word:"valiant", definition:"brave"})
			wordlist.addItem({word:"valorous", definition:"brave"})
			wordlist.addItem({word:"vanquish", definition:"conquer"})
			wordlist.addItem({word:"veer", definition:"change direction"})
			wordlist.addItem({word:"venal", definition:"ready to do smth dishonest"})
			wordlist.addItem({word:"veneer", definition:"surface appearance covering the TRUE nature"})
			wordlist.addItem({word:"veneration", definition:"regard with deep respect"})
			wordlist.addItem({word:"veracity", definition:"truth"})
			wordlist.addItem({word:"verdant", definition:"fresh and green"})
			wordlist.addItem({word:"verisimilitude", definition:"appearing TRUE or real"})
			wordlist.addItem({word:"veritable", definition:"real rightly named"})
			wordlist.addItem({word:"verve", definition:"spirit vigor enthusiasm"})
			wordlist.addItem({word:"vestige", definition:"trace or sign"})
			wordlist.addItem({word:"vex", definition:"annoy distress trouble"})
			wordlist.addItem({word:"vigilance", definition:"watchfulness self-appointed group who maintain order"})
			wordlist.addItem({word:"vigilant", definition:"member of a vigilance committee"})
			wordlist.addItem({word:"vigorous", definition:"strong energetic"})
			wordlist.addItem({word:"vilify", definition:"slander say evil things"})
			wordlist.addItem({word:"vindictive", definition:"having a desire to revenge"})
			wordlist.addItem({word:"virago", definition:"a loud domineering woman a scold or nag"})
			wordlist.addItem({word:"visceral", definition:"of the internal organs of the body"})
			wordlist.addItem({word:"viscous", definition:"sticky/semi-fluid"})
			wordlist.addItem({word:"vitiate", definition:"lower the quality weaken the strength"})
			wordlist.addItem({word:"vituperate", definition:"curse abuse in words"})
			wordlist.addItem({word:"vivacious", definition:"lively high-spirited"})
			wordlist.addItem({word:"volatile", definition:"changeable inconstant fickle unstable explosive"})
			wordlist.addItem({word:"volubility", definition:"fluency verbosity easy use of spoken language"})
			wordlist.addItem({word:"voluble", definition:"fluent"})
			wordlist.addItem({word:"waffle", definition:"talk vaguely and without much result"})
			wordlist.addItem({word:"waft", definition:"scent waving movement carry lightly through"})
			wordlist.addItem({word:"wag", definition:"merry person"})
			wordlist.addItem({word:"warmonger", definition:"person who stirs up war"})
			wordlist.addItem({word:"warrant", definition:"authority written order guarantee"})
			wordlist.addItem({word:"wean", definition:"to turn away (from a habit)"})
			wordlist.addItem({word:"weigh", definition:"measure hoe heavy smth is"})
			wordlist.addItem({word:"welter", definition:"turmoil a bewildering jumble"})
			wordlist.addItem({word:"wend", definition:"to go proceed"})
			wordlist.addItem({word:"whimsical", definition:"full of odd and fanciful ideas"})
			wordlist.addItem({word:"wince", definition:"show bodily or mental pain"})
			wordlist.addItem({word:"woo", definition:"try to win"})
			wordlist.addItem({word:"writ", definition:"written order"})
			wordlist.addItem({word:"yarn", definition:"tale story fibers for knitting"})
			
			doRandomSort(wordlist);
			
			return wordlist;
		}

		private static function doRandomSort(tempCollection:ICollectionView):void 
		{
			function randomCompare(a:Object, b:Object, fields:Array = null):int {
                		return Math.round(Math.random()*-1+Math.random());
            		}
			var sort:Sort = new Sort();
			sort.compareFunction = randomCompare;
			tempCollection.sort = sort;
			tempCollection.refresh();
		}
	}
}